# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant::Config.run do |config|
  config.vm.box = 'precise64'

  config.vm.define 'web' do |web|
    web.vm.forward_port 80, 8080
    web.vm.provision :shell, path: 'provision.sh'
    web.vm.provision :shell, inline: 'apt-get install -y mysql-client'
    web.vm.network :hostonly, '192.168.33.10'
  end

  config.vm.define 'db' do |db|
    db.vm.provision :shell, path: 'db_provision.sh'
    db.vm.network :hostonly, '192.168.33.11'
  end
end
