# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant::Config.run do |config|
  config.vm.box = 'precise64'
  config.vm.forward_port 80, 8080
  config.vm.provision 'shell', path: 'provision.sh'

end
